[project]
license = "CC0-1.0"
readme = "readme.md"
authors = [
  { name = "George King", email = "george@theorypractice.dev" },
]
dynamic = [
  "version",
]
name = "tolkien"
description = "Tolkien provides a simple `Token` type to allow various tokenizers to conform to the same interface."
requires-python = ">=3.14"
dependencies = []
keywords = [
  "generator",
  "grammar",
  "lex",
  "lexer",
  "lexing",
  "regex",
  "regular expression",
  "token",
  "tokenization",
  "tokenize",
  "tokenizer",
  "tokenizing",
  "unicode",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Typing :: Typed",
]

[project.urls]
Issues = "https://github.com/gwk/pithy/issues"
Source = "https://github.com/gwk/pithy"
Documentation = "https://github.com/gwk/pithy/tree/main/tolkien#readme"

[project.scripts]

[build-system]
requires = [
  "flit_core >= 4.0.2, < 5",
]
build-backend = "flit_core.buildapi"
