[project]
license = "CC0-1.0"
readme = "readme.md"
authors = [
  { name = "George King", email = "george@theorypractice.dev" },
]
dynamic = [
  "version",
]
name = "wu"
description = "Writeup is a document language that transforms to HTML."
requires-python = ">=3.14"
dependencies = [
  "legs",
  "pithy",
  "pygments >= 2.19.2",
  "tolkien",
]
keywords = [
  "HTML",
  "hypertext",
  "language",
  "markdown",
  "markup",
  "template",
  "writeup",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Typing :: Typed",
]

[project.urls]
Issues = "https://github.com/gwk/pithy/issues"
Source = "https://github.com/gwk/pithy"
Documentation = "https://github.com/gwk/pithy/tree/main/wu#readme"

[project.scripts]
writeup = "wu.bin.writeup:main"

[tool.uv.sources]
legs = { workspace = true }
pithy = { workspace = true }
tolkien = { workspace = true }

[build-system]
requires = [
  "flit_core >= 4.0.2, < 5",
]
build-backend = "flit_core.buildapi"
