// Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.

// Generated by `craft-py-rust-ext` from:
//   `_pyrrhus.pyi`
//   `byte_utils.pyi`
//   `str_utils/__init__.pyi`
// Do not edit. Each wrapper below converts its arguments/result and calls its hand-written implementation.

use pyo3::prelude::*;

// Assert that each implementation matches its declaration.
const _: fn() -> PyResult<String> = crate::_pyrrhus::hello_from_bin;
const _: fn(i64, i64) -> PyResult<i64> = crate::_pyrrhus::add;
const _: fn(Vec<f64>, f64) -> PyResult<Vec<f64>> = crate::_pyrrhus::scale;
const _: fn(&[u8]) -> PyResult<i64> = crate::byte_utils::sum_bytes;
const _: fn(&[u8], i64) -> PyResult<Option<i64>> = crate::byte_utils::find_byte;
const _: fn(&str, i64, &str) -> PyResult<String> = crate::str_utils::repeat;

/// Functions implemented in Rust.
#[allow(non_snake_case)]
#[pymodule]
pub mod _pyrrhus {
  use pyo3::prelude::*;

  /// Return a greeting from the Rust extension.
  #[pyfunction]
  fn hello_from_bin() -> PyResult<String> {
    crate::_pyrrhus::hello_from_bin()
  }

  /// Return the sum of `a` and `b`. Raises OverflowError if the sum does not fit in a signed 64-bit integer.
  #[pyfunction]
  #[pyo3(signature = (a, b))]
  fn add(a: i64, b: i64) -> PyResult<i64> {
    crate::_pyrrhus::add(a, b)
  }

  /// Return `values` multiplied by `factor`.
  #[pyfunction]
  #[pyo3(signature = (values, *, factor=1.0))]
  fn scale(values: Vec<f64>, factor: f64) -> PyResult<Vec<f64>> {
    crate::_pyrrhus::scale(values, factor)
  }

  // Declared in `byte_utils.pyi`.

  /// Return the sum of the byte values of `data`.
  #[pyfunction]
  #[pyo3(signature = (data))]
  fn byte_utils__sum_bytes(data: &[u8]) -> PyResult<i64> {
    crate::byte_utils::sum_bytes(data)
  }

  /// Return the index of the first occurrence of `byte` in `data`, or None if it is not present.
  #[pyfunction]
  #[pyo3(signature = (data, byte, /))]
  fn byte_utils__find_byte(data: &[u8], byte: i64) -> PyResult<Option<i64>> {
    crate::byte_utils::find_byte(data, byte)
  }

  // Declared in `str_utils/__init__.pyi`.

  /// Return `count` copies of `s`, joined by `sep`. Raises ValueError if `count` is negative.
  #[pyfunction]
  #[pyo3(signature = (s, count, sep=""))]
  fn str_utils__repeat(s: &str, count: i64, sep: &str) -> PyResult<String> {
    crate::str_utils::repeat(s, count, sep)
  }
}
