[project]
license = "CC0-1.0"
readme = "readme.md"
authors = [
  { name = "George King", email = "george@theorypractice.dev" },
]
dynamic = [
  "version",
]
name = "tomul"
description = "Tomul is a small library for reading and writing TOML files."
requires-python = ">=3.14"
dependencies = []
keywords = [
  "toml",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Typing :: Typed",
]

[project.urls]
Issues = "https://github.com/gwk/pithy/issues"
Source = "https://github.com/gwk/pithy"
Documentation = "https://github.com/gwk/pithy/tree/main/tomul#readme"

[project.scripts]

[build-system]
requires = [
  "flit_core >= 4.0.2, < 5",
]
build-backend = "flit_core.buildapi"
