# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.

from collections import defaultdict
from dataclasses import dataclass
from itertools import count
from time import perf_counter
from typing import Iterator

from pithy.dict import dict_put
from pithy.optional import unwrap

from . import DictLexerBase, ModeData
from .dfa import AmbiguityError, DFA, minimize_dfa
from .nfa import NFA, NfaState, NfaTransitions
from .parse import Grammar
from .patterns import LegsPattern, NfaMutableTransitions


def build_lexer_class(name:str, grammar:Grammar, encoding:str='utf-8') -> type[DictLexerBase]:
  '''
  Build a lexer class directly from a grammar, without generating source code.
  The result is equivalent to the class generated by the `python` output language.
  '''
  mode_data:dict[str,ModeData] = {
    dfa.name: (dfa.start_node, dfa.transitions, {node: unwrap(dfa.match_kind(node)) for node in dfa.match_nodes})
    for dfa in (automata.min_dfa for automata in build_mode_automata(grammar, encoding))}
  return type(name, (DictLexerBase,), dict(
    pattern_descs=build_pattern_descs(grammar), mode_transitions=grammar.transitions, mode_data=mode_data))


@dataclass
class ModeAutomata:
  'The automata built for one mode of a grammar. The earlier stages are kept for debugging, statistics and cross-checking.'
  mode:str
  nfa:NFA
  fat_dfa:DFA # The DFA as derived from the NFA, prior to minimization.
  min_dfa:DFA # The minimized DFA, from which lexers are generated.
  minimize_time:float # Seconds taken by minimization.



class ModeError(ValueError):
  '''
  Raised when the patterns of a mode are invalid, for example ambiguous.
  The automata that were built before the error was detected are provided for debugging.
  '''

  def __init__(self, msgs:list[str], nfa:NFA, fat_dfa:DFA|None=None):
    super().__init__('\n'.join(msgs))
    self.nfa = nfa
    self.fat_dfa = fat_dfa



def build_mode_automata(grammar:Grammar, encoding:str='utf-8') -> Iterator[ModeAutomata]:
  '''
  Build the automata for each mode of the grammar, yielding each mode as it is completed.
  The `main` mode is first, followed by the others in name order.
  The nodes of the minimized DFAs are numbered consecutively across the modes in this order.
  Raise ModeError if the patterns of a mode are invalid.
  '''
  start_node = 0
  for mode, kinds in sorted(grammar.modes.items(), key=lambda item: mode_name_key(item[0])):
    nfa = build_nfa(name=mode, named_patterns=sorted((kind, grammar.patterns[kind]) for kind in kinds), encoding=encoding)
    msgs = nfa.validate()
    if msgs: raise ModeError(msgs, nfa)
    fat_dfa = build_dfa(nfa)
    start_time = perf_counter()
    try: min_dfa = minimize_dfa(fat_dfa, start_node=start_node)
    except AmbiguityError as e: raise ModeError(e.msgs, nfa, fat_dfa) from e
    minimize_time = perf_counter() - start_time
    start_node = min_dfa.end_node
    yield ModeAutomata(mode=mode, nfa=nfa, fat_dfa=fat_dfa, min_dfa=min_dfa, minimize_time=minimize_time)


def mode_name_key(name:str) -> str:
  'Always place main mode first.'
  return '' if name == 'main' else name


def build_pattern_descs(grammar:Grammar) -> dict[str,str]:
  'Return the description of each token kind, including `invalid` and `incomplete`.'
  pattern_descs = {kind: pattern.literal_desc or kind for kind, pattern in grammar.patterns.items()}
  pattern_descs.update((kind, kind) for kind in ['invalid', 'incomplete'])
  return pattern_descs


def build_nfa(name:str, named_patterns:list[tuple[str, LegsPattern]], encoding:str) -> NFA:
  '''
  Generate an NFA from a set of patterns.
  The NFA can be used to match against an argument string,
  but cannot produce a token stream directly.
  The `invalid` node is unreachable, and reserved for later use by the derived DFA.
  '''

  indexer = iter(count())
  def mk_node() -> int: return next(indexer)

  start = mk_node() # always 0; see build_dfa.
  invalid = mk_node() # always 1; see build_dfa.

  match_node_kinds:dict[int,str] = { invalid: 'invalid' }

  transitions_dd:NfaMutableTransitions = defaultdict(lambda: defaultdict(set))
  for kind, pattern in named_patterns:
    match_node = mk_node()
    pattern.gen_nfa(mk_node, encoding, transitions_dd, start, match_node)
    dict_put(match_node_kinds, match_node, kind)
  lit_pattern_names = { n for n, pattern in named_patterns if pattern.is_literal }

  transitions:NfaTransitions = {
    src: {char: frozenset(dst) for char, dst in d.items() } for src, d in transitions_dd.items() }
  return NFA(name=name, encoding=encoding, transitions=transitions, match_node_kinds=match_node_kinds, lit_pattern_names=lit_pattern_names)


def build_dfa(nfa:NFA) -> DFA:
  '''
  Build a DFA from an NFA.

  Conceptually, a DFA node is equivalent to a set of NFA nodes.
  Note that this is easily confused with an NFA state (also a set of NFA nodes).
  A DFA has a node for every reachable subset of nodes in the corresponding NFA.
  In the worst case, there will be an exponential increase in number of nodes.

  Unlike the NFA, the DFA's operational state is just a single node value.

  For each DFA node, there is a mapping from byte values to destination nodes.
  Conceputally, generating a lexer from a DFA is straightforward:
  switch on the current state, and then switch on the current byte.
  '''

  indexer = iter(count())
  def mk_node() -> int: return next(indexer)

  nfa_states_to_dfa_nodes = defaultdict[NfaState, int](mk_node)
  start = nfa.advance_empties({0})
  invalid = frozenset({1}) # no need to advance_empties as `invalid` is unreachable in the nfa.
  start_node = nfa_states_to_dfa_nodes[start]
  invalid_node = nfa_states_to_dfa_nodes[invalid]

  transitions = defaultdict[int,dict[int,int]](dict)
  alphabet = nfa.alphabet
  remaining = {start}
  while remaining:
    state = remaining.pop()
    node = nfa_states_to_dfa_nodes[state]
    d = transitions[node] # unlike NFA, DFA dictionary contains all valid nodes/states as keys.
    for char in alphabet:
      dst_state = frozenset(nfa.advance(state, char))
      if not dst_state: continue # do not add empty sets.
      dst_node = nfa_states_to_dfa_nodes[dst_state]
      d[char] = dst_node
      if dst_node not in transitions:
        remaining.add(dst_state)

  # Explicitly add transitions to and from `invalid`, which is otherwise not reachable.
  # `start` transitions to `invalid` for all bytes not yet covered.
  # `invalid` transitions to itself for those same bytes.
  assert invalid_node not in transitions
  start_dict = transitions[start_node]
  invalid_dict = transitions[invalid_node]
  whole_alphabet = set(range(2**8 if nfa.encoding else 2**32))
  invalid_start_chars = whole_alphabet.difference(start_dict)
  for c in invalid_start_chars:
    start_dict[c] = invalid_node
    invalid_dict[c] = invalid_node

  # Generate match_node_kind_sets.
  node_kinds = defaultdict[int, set[str]](set) # nodes to sets of kinds.
  for nfa_state, dfa_node in nfa_states_to_dfa_nodes.items():
    for nfa_node in nfa_state:
      try: kind = nfa.match_node_kinds[nfa_node]
      except KeyError: continue
      node_kinds[dfa_node].add(kind)
  match_node_kind_sets = { node : frozenset(kinds) for node, kinds in node_kinds.items() }

  return DFA(name=nfa.name, transitions=dict(transitions), match_node_kind_sets=match_node_kind_sets, lit_pattern_names=nfa.lit_pattern_names)