# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.

'''
Property checks for the lexer built from a legs grammar, using inputs generated from the grammar itself.

The checks compare the table-driven lexer to the NFA of each mode, which is built directly from the patterns
and is independent of DFA construction and minimization.
For each token that the lexer produces:
* the tokens cover the input exactly, in order, with no gaps, overlaps or empty tokens;
* the token is the longest prefix that the NFA matches at that position, and its kind is one that the NFA matches;
  if a literal pattern is among those matched, then the kind is that of a literal pattern;
* if the NFA matches no prefix then the token kind is `invalid` or `incomplete`.

The inputs come from four sources:
* strings generated to match each pattern, which must lex as a single token;
* sequences of such strings that follow the mode transitions, so that the text is well nested;
* sequences of such strings from all modes, mixed with arbitrary characters and bytes;
* a deterministic set that traverses every transition of each minimized DFA.
The first three are generated by Hypothesis, which shrinks a failing input to a minimal one.

The generated strings find a lexer that matches less than the patterns specify, or matches the wrong kind.
The DFA traversal finds a lexer that matches more than the patterns specify, because it follows the transitions of the DFA
from which the lexer is built, including any that the patterns do not justify.
'''

from dataclasses import dataclass
from functools import partial
from typing import Callable, Iterator

from hypothesis import given, settings, strategies as st
from hypothesis.strategies import SearchStrategy
from tolkien import Source

from . import DictLexerBase
from .build import build_lexer_class_for_automata, build_mode_automata, ModeAutomata
from .dfa import DFA
from .nfa import NFA
from .parse import Grammar
from .patterns import CharsetPattern, ChoicePattern, LegsPattern, OptPattern, PlusPattern, SeqPattern, StarPattern


@dataclass
class PropsStats:
  'Counts of the inputs that were checked.'
  single_token_examples:int = 0
  nested_examples:int = 0
  sequence_examples:int = 0
  coverage_inputs:int = 0



class PropertyError(AssertionError):
  'Raised when a lexer violates a property. The message describes the input and the offending token.'



class GrammarChecker:
  'The lexer and automata of a grammar, with the property checks.'

  def __init__(self, grammar:Grammar, automata:list[ModeAutomata]|None=None, Lexer:type[DictLexerBase]|None=None):
    '''
    `automata` and `Lexer` are built from the grammar if they are not provided.
    Providing a lexer allows a lexer from another source to be checked against the automata.
    '''
    self.grammar = grammar
    if automata is None: automata = list(build_mode_automata(grammar))
    self.automata = {a.mode: a for a in automata}
    self.Lexer = Lexer or build_lexer_class_for_automata('CheckedLexer', grammar, automata)


  def check_all(self, max_examples:int=100, derandomize:bool=True, coverage_limit:int|None=None) -> PropsStats:
    '''
    Run all of the checks. Raise PropertyError for the first violation; Hypothesis shrinks generated inputs first.
    `max_examples` is the number of generated examples per pattern and per mode.
    `derandomize` makes Hypothesis generate the same examples on every run.
    `coverage_limit` caps the number of DFA coverage inputs per mode.
    '''
    stats = PropsStats()
    hyp_settings = settings(max_examples=max_examples, derandomize=derandomize, database=None, deadline=None)

    def run[T](strategy:SearchStrategy[T], check:Callable[[T],None]) -> None:
      'Run `check` on examples generated by `strategy`.'
      @hyp_settings
      @given(strategy)
      def test(example:T) -> None: check(example)
      test()

    def check_single(mode:str, kind:str, text:str) -> None:
      stats.single_token_examples += 1
      self.check_single_token(text.encode(), mode, kind)

    def check_nested(mode:str, text:str) -> None:
      stats.nested_examples += 1
      self.check_tokens(text.encode(), mode)

    def check_sequence(mode:str, text:bytes) -> None:
      stats.sequence_examples += 1
      self.check_tokens(text, mode)

    text_strategy = grammar_text_strategy(self.grammar)
    for mode, automata in self.automata.items():
      for kind in sorted(self.grammar.modes[mode]):
        strategy = pattern_strategy(self.grammar.patterns[kind])
        if strategy.is_empty: continue # The pattern matches nothing, for example an empty charset.
        run(strategy, partial(check_single, mode, kind))
      run(mode_text_strategy(self.grammar, mode), partial(check_nested, mode))
      run(text_strategy, partial(check_sequence, mode))
      for text in dfa_coverage_inputs(automata.min_dfa, limit=coverage_limit):
        stats.coverage_inputs += 1
        self.check_tokens(text, mode)

    return stats


  def check_single_token(self, text:bytes, mode:str, kind:str) -> None:
    'Check that `text`, which was generated to match the pattern of `kind`, lexes as a single token.'
    self.check_tokens(text, mode)
    length, kinds = nfa_longest_match(self.automata[mode].nfa, text, 0)
    if length != len(text) or kind not in kinds:
      raise PropertyError(f'mode {mode!r}: text generated for pattern {kind!r} is not matched by the NFA as that kind: '
        f'{text!r}; NFA longest match: {length} bytes; kinds: {sorted(kinds)}.')
    tokens = list(self.Lexer(Source('input', text), mode=mode))
    if len(tokens) != 1:
      raise PropertyError(f'mode {mode!r}: text generated for pattern {kind!r} does not lex as a single token: {text!r}; '
        f'tokens: {[(t.kind, t.pos, t.end) for t in tokens]}.')


  def check_tokens(self, text:bytes, mode:str) -> None:
    'Check the tokens that the lexer produces for `text`, starting in `mode`.'
    stack:list[tuple[str,str|None]] = [(mode, None)] # An independent simulation of the mode stack: (mode, pop_kind).
    pos = 0
    for token in self.Lexer(Source('input', text), mode=mode):
      def fail(msg:str) -> PropertyError:
        return PropertyError(f'mode {mode!r}: input {text!r}: token {token.kind}:{token.pos}-{token.end}: {msg}')

      if token.pos != pos: raise fail(f'token does not begin at the end of the previous token: {pos}.')
      if token.end <= token.pos: raise fail('token is empty.')
      if token.end > len(text): raise fail('token extends past the end of the input.')
      curr_mode, pop_kind = stack[-1]
      if token.mode != curr_mode: raise fail(f'token mode is {token.mode!r}; expected {curr_mode!r}.')

      nfa = self.automata[curr_mode].nfa
      length, kinds = nfa_longest_match(nfa, text, pos)
      kinds = (kinds & nfa.lit_pattern_names) or kinds # A literal pattern takes precedence.
      if length:
        if token.end - token.pos != length: raise fail(f'NFA longest match is {length} bytes; kinds: {sorted(kinds)}.')
        if token.kind not in kinds: raise fail(f'NFA matches kinds: {sorted(kinds)}.')
      elif token.kind not in ('invalid', 'incomplete'):
        raise fail('NFA matches no prefix; expected `invalid` or `incomplete`.')

      if token.kind == pop_kind: stack.pop()
      else:
        try: stack.append(self.grammar.transitions[curr_mode][token.kind])
        except KeyError: pass
      pos = token.end
    if pos != len(text): raise PropertyError(f'mode {mode!r}: input {text!r}: tokens end at {pos}; expected {len(text)}.')



def nfa_longest_match(nfa:NFA, text:bytes, pos:int) -> tuple[int,frozenset[str]]:
  '''
  Return the length of the longest prefix of `text[pos:]` that the NFA matches, and the kinds matched.
  The length is 0 if no prefix matches.
  '''
  state = nfa.advance_empties({0})
  length = 0
  kinds = frozenset[str]()
  for i in range(pos, len(text)):
    state = nfa.advance(state, text[i])
    if not state: break
    state_kinds = frozenset(nfa.match_node_kinds[node] for node in state if node in nfa.match_node_kinds)
    if state_kinds:
      length = i + 1 - pos
      kinds = state_kinds
  return (length, kinds)


def pattern_strategy(pattern:LegsPattern) -> SearchStrategy[str]:
  'Return a strategy that generates strings matching the pattern.'
  match pattern:
    case CharsetPattern(): return charset_strategy(pattern)
    case SeqPattern(): return st.tuples(*(pattern_strategy(sub) for sub in pattern)).map(''.join)
    case ChoicePattern(): return st.one_of(*(pattern_strategy(sub) for sub in pattern))
    case OptPattern(): return st.just('') | pattern_strategy(pattern.sub)
    case StarPattern(): return st.lists(pattern_strategy(pattern.sub), max_size=max_repetitions).map(''.join)
    case PlusPattern(): return st.lists(pattern_strategy(pattern.sub), min_size=1, max_size=max_repetitions).map(''.join)
    case _: raise NotImplementedError(pattern)


max_repetitions = 4


def charset_strategy(pattern:CharsetPattern) -> SearchStrategy[str]:
  'Return a strategy that generates the characters of a charset, favoring the ends of each range. Surrogates are omitted.'
  ranges:list[tuple[int,int]] = [] # Inclusive (start, last) ranges.
  for start, end in pattern.ranges:
    for s, l in ((start, min(end, 0xD800) - 1), (max(start, 0xE000), end - 1)): # Split around the surrogates.
      if s <= l: ranges.append((s, l))
  if not ranges: return st.nothing()
  ends = sorted({code for r in ranges for code in r})
  return (st.sampled_from(ends) | st.sampled_from(ranges).flatmap(lambda r: st.integers(r[0], r[1]))).map(chr)


def mode_text_strategy(grammar:Grammar, mode:str, depth:int=3) -> SearchStrategy[str]:
  '''
  Return a strategy that generates sequences of strings matching the patterns of `mode`.
  A string whose kind has a mode transition is followed by text for the pushed mode and then a string of the closing kind,
  so that the text exercises the mode stack. `depth` limits the nesting.
  '''
  strategies = {kind: pattern_strategy(pattern) for kind, pattern in grammar.patterns.items()}
  mode_kinds = {m: sorted(kind for kind in kinds if not strategies[kind].is_empty) for m, kinds in grammar.modes.items()}

  @st.composite
  def mode_text(draw:st.DrawFn, mode:str, depth:int) -> str:
    # A composite strategy is used because the nesting is decided as the text is drawn.
    kinds = mode_kinds[mode]
    if not kinds: return ''
    parts:list[str] = []
    for kind in draw(st.lists(st.sampled_from(kinds), max_size=6)):
      parts.append(draw(strategies[kind]))
      try: push_mode, close_kind = grammar.transitions[mode][kind]
      except KeyError: continue
      if depth: parts.append(draw(mode_text(push_mode, depth - 1)))
      if not strategies[close_kind].is_empty: parts.append(draw(strategies[close_kind]))
    return ''.join(parts)

  return mode_text(mode, depth)


def grammar_text_strategy(grammar:Grammar) -> SearchStrategy[bytes]:
  '''
  Return a strategy that generates sequences of strings matching the patterns of the grammar,
  mixed with printable ASCII characters and arbitrary bytes.
  The patterns of all modes are used, so that each mode also receives text that it cannot match.
  '''
  pattern_strategies = [pattern_strategy(grammar.patterns[kind]) for kind in sorted(grammar.patterns)]
  parts = [s.map(str.encode) for s in pattern_strategies if not s.is_empty]
  parts.append(st.integers(0x20, 0x7E).map(lambda code: bytes([code])))
  parts.append(st.binary(min_size=1, max_size=3))
  return st.lists(st.one_of(*parts), max_size=8).map(b''.join)


def dfa_coverage_inputs(dfa:DFA, limit:int|None=None) -> Iterator[bytes]:
  '''
  Yield inputs that together traverse every transition of the DFA at least once, up to `limit` inputs.
  Each input is the shortest path from the start node to a node, followed by one further byte.
  The transitions of a node are grouped into runs of consecutive bytes that lead to the same destination;
  the first and last byte of each run are used.
  Inputs that end in a node that follows a match node without itself matching exercise the lexer's backtracking.
  '''
  paths:dict[int,bytes] = {dfa.start_node: b''}
  queue = [dfa.start_node]
  count = 0
  for node in queue: # The queue grows during iteration; this is a breadth-first traversal.
    transitions = dfa.transitions.get(node, {})
    for byte, dst in sorted(transitions.items()):
      is_run_start = (transitions.get(byte - 1) != dst)
      is_run_end = (transitions.get(byte + 1) != dst)
      if not (is_run_start or is_run_end): continue
      text = paths[node] + bytes([byte])
      if dst not in paths:
        paths[dst] = text
        queue.append(dst)
      if limit is not None and count >= limit: return
      count += 1
      yield text
