[project]
license = "CC0-1.0"
readme = "readme.md"
authors = [
  { name = "George King", email = "george@theorypractice.dev" },
]
dynamic = [
  "version",
]
name = "legs"
description = "Legs is a lexer generator."
requires-python = ">=3.14"
dependencies = [
  "pithy",
]
keywords = [
  "generator",
  "grammar",
  "lex",
  "lexer",
  "lexing",
  "regex",
  "regular expression",
  "token",
  "tokenization",
  "tokenize",
  "tokenizer",
  "tokenizing",
  "unicode",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Topic :: Software Development :: Code Generators",
  "Typing :: Typed",
]

[project.urls]
Issues = "https://github.com/gwk/pithy/issues"
Source = "https://github.com/gwk/pithy"
Documentation = "https://github.com/gwk/pithy/tree/main/legs#readme"

[project.optional-dependencies]
dev = [
  "mypy >= 1.20.1",
  "pyflakes >= 3.4.0",
  "isort >= 8.0.1",
]

[project.scripts]
legs = "legs.bin.legs:main"

[project.package-data]
legs = [
  "py.typed",
]

[build-system]
requires = [
  "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
  "legs/**/*",
]
exclude = [
  "legs/**/__pycache__/**/*",
]

[tool.hatch.version]
path = "legs/__about__.py"
