# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.
# Generated by craft-py-rust-ext. Do not edit.

from .._pyrrhus import str_utils__repeat as repeat


__all__ = [
  'repeat',
]
