
[project]

name = "iotest"
description = "IOTest is a process/integration test harness that captures standard IO as the basis for test validation."
requires-python = ">=3.14"

dependencies = [
  "pithy"
]

keywords = [
  "io",
  "test",
  "testing",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Topic :: Software Development :: Testing",
  "Typing :: Typed",
]
