[project]
license = "CC0-1.0"
readme = "readme.md"
authors = [
  { name = "George King", email = "george@theorypractice.dev" },
]
dynamic = [
  "version",
]
name = "iotest"
description = "IOTest is a process/integration test harness that captures standard IO as the basis for test validation."
requires-python = ">=3.14"
dependencies = [
  "pithy",
]
keywords = [
  "io",
  "test",
  "testing",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Topic :: Software Development :: Testing",
  "Typing :: Typed",
]

[project.urls]
Issues = "https://github.com/gwk/pithy/issues"
Source = "https://github.com/gwk/pithy"
Documentation = "https://github.com/gwk/pithy/tree/main/iotest#readme"

[project.scripts]
iotest = "iotest.bin.iotest:main"

[tool.uv.sources]
pithy = { workspace = true }

[build-system]
requires = [
  "flit_core >= 4.0.2, < 5",
]
build-backend = "flit_core.buildapi"
