# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.

import re

from argparse import Namespace
from typing import *
from pithy.fs import add_file_execute_permissions
from pithy.io import *
from pithy.string_utils import render_template

from .defs import ModeTransitions
from .rules import ModeNamedRules

def output_python(mode_named_rules: ModeNamedRules, mode_transitions: ModeTransitions, license: str, args: Namespace):
  path = args.output
  patterns: List[str] = []
  modes: List[str] = []
  for mode, named_rules in sorted(mode_named_rules.items()):
    names_str = ''.join(f'\n      {n!r},' for n, _ in named_rules)
    modes.append(f'\n    {mode}={{{names_str}}}')
    for name, rule in named_rules:
      pattern = rule.genRegex(flavor='py')
      patterns.append(f"\n    {name}=r'{pattern}',")

  transitions: List[str] = [f'\n    ({a}, {b}) : ({c}, {d})' for (a, b), (c, d) in mode_transitions.items()]

  with open(path, 'w', encoding='utf8') as f:
    if args.test:
      f.write('#!/usr/bin/env python3\n')
    src = render_template(template,
      license=license,
      rules_path=args.rules_path,
      patterns=''.join(patterns),
      modes=''.join(modes),
      transitions=''.join(transitions),
    )
    f.write(src)
    if args.test:
      test_src = render_template(test_template)
      f.write(test_src)
      add_file_execute_permissions(f.fileno())


template = r'''# ${license}
# This file was generated by legs from ${rules_path}.

from pithy.lex import Lexer, msg_for_match


lexer = Lexer(
  invalid='invalid',
  patterns=dict(${patterns}),
  modes=dict(${modes}),
  transitions={${transitions}})
'''


test_template = r'''
def main() -> None:
  from sys import argv
  for i, arg in enumerate(argv):
    if i == 0: continue
    test(index=i, arg=arg)

def test(index: int, arg: str) -> None:
  print(f'arg{index}: {arg!r}')
  for token in lexer.lex(arg):
    print(msg_for_match(token, prefix='token', msg=token.lastgroup))

if __name__ == '__main__': main()
'''
