[project]
license = "CC0-1.0"
authors = [
    { name = "George King", email = "george@theorypractice.dev" },
]
dynamic = [
    "version",
]
readme = "legs/readme.md"
name = "legs"
description = "Legs is a lexer generator."
requires-python = ">=3.14"
dependencies = []
keywords = [
    "generator",
    "grammar",
    "lex",
    "lexer",
    "lexing",
    "regex",
    "regular expression",
    "token",
    "tokenization",
    "tokenize",
    "tokenizer",
    "tokenizing",
    "unicode",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "Topic :: Software Development :: Code Generators",
    "Typing :: Typed",
]

[project.urls]
Issues = "https://github.com/gwk/pithy/issues"
Source = "https://github.com/gwk/pithy"
Documentation = "https://github.com/gwk/pithy/tree/main/legs#readme"

[project.scripts]
legs = "legs.bin.legs:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "legs/**/*",
]
exclude = [
    "legs/**/__pycache__/**/*",
    "legs/project.toml",
]

[tool.hatch.version]
path = "legs/__about__.py"
