#!/usr/bin/env python3
# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.

'''
Generate `pithy.unicode.data` from the Unicode Character Database.
The source files are fetched from unicode.org into the cache directory unless they are already present.
'''

import re
from collections import defaultdict
from io import StringIO
from itertools import chain
from pathlib import Path
from typing import Iterator
from urllib.request import urlopen

from pithy.cmdparse import Cmd, opt, pos
from pithy.unicode import coalesce_sorted_ranges, CodeRange, codes_for_ranges, ranges_for_codes


class GenUnicodeData(Cmd):
  'Generate `pithy.unicode.data` from the Unicode Character Database.'

  version:str = pos(doc='Unicode version, e.g. `18.0.0`.')
  cache:str = opt(default='_build/unicode-data', doc='Directory in which the source files of each version are cached.')
  output:str = opt(default='pithy_/pithy/unicode/data.py', doc='Path of the generated module.')


def main() -> None:
  args = GenUnicodeData.parse_or_exit()
  version = args.version
  if not version_re.fullmatch(version): raise SystemExit(f'error: expected a version like `18.0.0`; received: {version!r}')

  source_dir = Path(args.cache) / version
  for name in source_names:
    fetch_source(version, name, source_dir / name)

  blocks_path = source_dir / blocks_name
  blocks_version = parse_blocks_version(blocks_path)
  if blocks_version != version:
    raise SystemExit(f'error: {blocks_path}: file version is {blocks_version!r}; expected {version!r}.')

  out = StringIO()
  def outL(*items:str, end:str='\n') -> None: print(*items, sep='', end=end, file=out)

  outL('# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.')
  outL('# Derived from data published by the Unicode Consortium; see: http://unicode.org/copyright.html.')
  outL('# Generated by github.com/gwk/pithy tools/gen-unicode-data.py.')
  outL(f'# Source: {source_url(version, "")}.')
  outL('\n')

  outL(f'unicode_version = {version!r}')
  outL('\n')

  block_names_to_codes = { name.replace(' ', '_').replace('-', '_') : codes for codes, (name,) in parse_rows(blocks_path) }

  outL('blocks: dict[str, tuple[int, int]] = {')
  for name, codes in sorted(block_names_to_codes.items(), key=lambda p: p[1]):
    outL(f'  {name!r}: {repr_pair(codes)},')
  outL('}\n\n')

  category_ranges = defaultdict[str,list[CodeRange]](list)
  for codes, (cat,) in parse_rows(source_dir / categories_name):
    category_ranges[cat].append(codes)

  # Verify that the category ranges cover the entire space.
  all_ranges = sorted(chain(*category_ranges.values()))
  if tuple(coalesce_sorted_ranges(all_ranges)) != ((0, 0x110000),):
    raise SystemExit(f'error: {categories_name}: category ranges do not cover the code space.')

  outL('category_ranges: dict[str, tuple[tuple[int, int], ...]] = {')
  for cat, codes_seq in sorted(category_ranges.items()):
    outL(f'  {cat!r}: (', end='')
    for i, codes in enumerate(codes_seq):
      outL((' ' if i % 4 else '\n    '), repr_pair(codes), ',', end='')
    outL('\n  ),\n')
  outL('}\n\n')

  # Terminal double width ranges.
  # Unassigned code points take their width from the `@missing` defaults; the explicit rows then override those.
  east_asian_path = source_dir / east_asian_name
  double_codes = set(codes_for_ranges(parse_missing_rows(east_asian_path, values=('Fullwidth', 'Wide'))))
  for codes, (width,) in parse_rows(east_asian_path):
    if width in ('F', 'W'): double_codes.update(range(*codes))
    else: double_codes.difference_update(range(*codes))

  outL("double_width_codes: list[tuple[int, int]] = [ # Code points with East Asian Width 'W' or 'F'.", end='')
  for i, codes in enumerate(ranges_for_codes(sorted(double_codes))):
    outL((' ' if i % 4 else '\n  '), repr_pair(codes), ',', end='')
  outL('\n]')

  # Write the output last, so that a failure does not truncate the existing module.
  Path(args.output).write_text(out.getvalue())


blocks_name = 'Blocks.txt'
categories_name = 'extracted/DerivedGeneralCategory.txt'
east_asian_name = 'extracted/DerivedEastAsianWidth.txt'
source_names = (blocks_name, categories_name, east_asian_name)

version_re = re.compile(r'\d+\.\d+\.\d+')
blocks_version_re = re.compile(r'# Blocks-(\d+\.\d+\.\d+)\.txt')
missing_re = re.compile(r'# @missing: ([0-9A-F.]+); (\w+)')


def source_url(version:str, name:str) -> str:
  return f'https://www.unicode.org/Public/{version}/ucd/{name}'


def fetch_source(version:str, name:str, path:Path) -> None:
  if path.exists(): return
  url = source_url(version, name)
  print(f'fetching: {url}')
  with urlopen(url) as response:
    data = response.read()
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_bytes(data)


def parse_blocks_version(path:Path) -> str:
  with path.open() as f:
    first_line = f.readline()
  m = blocks_version_re.match(first_line)
  if not m: raise SystemExit(f'error: {path}: first line does not declare a version: {first_line!r}')
  return m[1]


type Row = tuple[CodeRange, tuple[str,...]]

def parse_rows(path:Path) -> Iterator[Row]:
  with path.open() as f:
    for line in f:
      line, _, _ = line.partition('#')
      line = line.strip()
      if not line: continue
      els = line.split(';')
      yield (parse_codes(els[0]), tuple(el.strip() for el in els[1:]))


def parse_missing_rows(path:Path, values:tuple[str,...]) -> Iterator[CodeRange]:
  'Yield the ranges of the `@missing` comment lines, which declare default values, for the given long value names.'
  with path.open() as f:
    for line in f:
      m = missing_re.match(line)
      if m and m[2] in values: yield parse_codes(m[1])


def parse_codes(string:str) -> CodeRange:
  low, dots, high = string.partition('..')
  l = int(low, base=16)
  if dots: return (l, int(high, base=16) + 1) # Add one to produce end index.
  else: return (l, l + 1)


def repr_pair(pair:CodeRange) -> str:
  return '(0x{:04X}, 0x{:04X})'.format(*pair)


if __name__ == '__main__': main()
