
[project]

name = "crafts"
description = "Crafts is a set of custom build tools."
requires-python = ">=3.14"

dependencies = [
  "pithy",
  "PyYAML >= 6.0.3",
]

keywords = [
  "build",
  "tool",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Typing :: Typed",
]
