
[project]

name = "pithy"
description = "Pithy is a collection of utility libraries for Python 3."
requires-python = ">=3.14"

dependencies = [
  "blake3 >= 1.0.8",
  "brotli >= 1.2.0",
  "cryptography >= 46.0.3",
  "docutils >= 0.22.3",
  "lxml >= 6.0.2",
  "msgpack >= 1.1.2",
  "msgpack-types >= 0.5.0",
  "mypy >= 1.19.1",
  "mypy-extensions >= 1.1.0",
  "python-multipart >= 0.0.26",
  "pyyaml >= 6.0.3",
  "starlette >= 0.50",
  "types-lxml >= 2025.8.25",
  "types-PyYAML >= 6.0.12.20250915",
  "requests >= 2.33.1",
  "pyflakes >= 3.4.0",
]

keywords = [
  "ansi",
  "chart",
  "console",
  "csv",
  "diff",
  "format",
  "graph",
  "graphviz",
  "html",
  "json",
  "lex",
  "lexer",
  "lexing",
  "parse",
  "parser",
  "parsing",
  "sqlite",
  "svg",
]

classifiers = [
  "Environment :: Console",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Programming Language :: Python :: 3",
  "Typing :: Typed",
]
