
[project]

name = "pithytools"
description = "Pithytools is a collection of comamnd line utilities that depend on the `pithy` package."
requires-python = ">=3.14"

dependencies = [
  "packaging >= 25.0",
  "pillow >= 12.0.0",
  "pithy",
]

keywords = [
  "console",
  "crawl",
  "csv",
  "diff",
  "format",
  "graph",
  "graphviz",
  "html",
  "json",
  "msgpack",
  "parse",
  "parser",
  "parsing",
  "scrape",
  "scraper",
  "scraping",
  "sqlite",
  "svg",
  "syntax",
  "term",
  "terminal",
  "unicode",
  "utilities",
  "xml",
  "zst",
  "zstd",
  "zstandard",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Environment :: Console",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Programming Language :: Python :: 3",
  "Topic :: Documentation",
  "Topic :: Education",
  "Topic :: Internet",
  "Topic :: Multimedia",
  "Topic :: Office/Business",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Software Development :: Documentation",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Pre-processors",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: User Interfaces",
  "Topic :: Software Development :: Version Control",
  "Topic :: Software Development :: Version Control :: Git",
  "Topic :: System",
  "Topic :: Text Processing",
  "Topic :: Text Processing :: Filters",
  "Topic :: Text Processing :: General",
  "Topic :: Text Processing :: Markup",
  "Topic :: Text Processing :: Markup :: HTML",
  "Topic :: Utilities",
  "Typing :: Typed",
]
