
[project]

name = "pithytools"
description = "Pithytools is a collection of comamnd line utilities that depend on the `pithy` package."
requires-python = ">=3.14"

dependencies = [
  "packaging >= 25.0",
  "pillow >= 12.0.0",
  "pithy",
]

keywords = []

classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Typing :: Typed",
]
