
[project]

name = "pithy"
description = "Pithy is a collection of utility libraries for Python 3."
requires-python = ">=3.14"

dependencies = [
  "brotli >= 1.1.0",
  "mypy >= 1.18.2",
  "mypy-extensions >= 1.1.0",
  "cryptography-46.0.2",
  "starlette-0.48.0",
  "types-PyYAML >= 6.0.12.20250915",
  "lxml >= 6.0.2",
  "blake3 >= 1.0.7",
  "types-lxml >= 2025.8.25",
  "msgpack >= 1.1.2",
  "msgpack-types >= 0.5.0",
  "docutils >= 0.22.0",
]

keywords = [
  "ansi",
  "apfs",
  "buffer",
  "chart",
  "clone",
  "console",
  "crawl",
  "csv",
  "diff",
  "format",
  "graph",
  "graphviz",
  "html",
  "iterable",
  "json",
  "lex",
  "lexer",
  "lexing",
  "msgpack",
  "parse",
  "parser",
  "parsing",
  "scrape",
  "scraping",
  "sqlite",
  "svg",
  "syntax",
  "test",
  "testing",
  "term",
  "terminal",
  "token",
  "tokenization",
  "tokenizer",
  "types",
  "typing",
  "unicode",
  "unit",
  "utilities",
  "xml",
  "zst",
  "zstd",
  "zstandard",
]

classifiers = [
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Programming Language :: Python :: 3",
  "Topic :: Documentation",
  "Topic :: Education",
  "Topic :: Internet",
  "Topic :: Multimedia",
  "Topic :: Office/Business",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Software Development :: Documentation",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Pre-processors",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: User Interfaces",
  "Topic :: Software Development :: Version Control",
  "Topic :: Software Development :: Version Control :: Git",
  "Topic :: System",
  "Topic :: Text Processing",
  "Topic :: Text Processing :: Filters",
  "Topic :: Text Processing :: General",
  "Topic :: Text Processing :: Markup",
  "Topic :: Text Processing :: Markup :: HTML",
  "Topic :: Utilities",
  "Typing :: Typed",
]
