
[project]

name = "tolkien"
description = "Tolkien provides a simple `Token` type to allow various tokenizers to conform to the same interface."
requires-python = ">=3.12"

dependencies = []

keywords = [
  "generator",
  "grammar",
  "lex",
  "lexer",
  "lexing",
  "regex",
  "regular expression",
  "token",
  "tokenization",
  "tokenize",
  "tokenizer",
  "tokenizing",
  "unicode",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Pre-processors",
  "Topic :: System",
  "Topic :: Text Processing",
  "Topic :: Utilities",
  "Typing :: Typed",
]
