
[project]

name = "utest"
description = "UTest is a simple unit-testing library."
requires-python = ">=3.14"

dependencies = []

keywords = [
  "unit",
  "test",
  "testing",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Typing :: Typed",
]
