
[project]

name = "wu"
description = "Writeup is a document language that transforms to HTML."
requires-python = ">=3.12"

dependencies = [
  "pithy",
  "pygments >= 2.19.2",
  "types-pygments >= 2.19.0.20250809",
]

keywords = [
  "HTML",
  "hypertext",
  "language",
  "markdown",
  "markup",
  "template",
  "writeup",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Programming Language :: Python :: 3",
  "Topic :: Documentation",
  "Topic :: Education",
  "Topic :: Internet",
  "Topic :: Multimedia",
  "Topic :: Office/Business",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Software Development :: Documentation",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Pre-processors",
  "Topic :: Software Development :: User Interfaces",
  "Topic :: System",
  "Topic :: Text Processing",
  "Topic :: Text Processing :: General",
  "Topic :: Text Processing :: Markup",
  "Topic :: Text Processing :: Markup :: HTML",
  "Typing :: Typed",
]
